#!/usr/bin/env bash

#Make this file executable by chmod 700
# Make my .vim directories for plugins and undo history
mkdir -p ~/.local/share/nvim/site/pack/plugs/start
mkdir ~/.config/nvim/undodir
# Clone the plugins
cd ~/.local/share/nvim/site/pack/plugs/start
git clone https://github.com/vim-scripts/AutoComplPop.git
git clone https://github.com/morhetz/gruvbox.git
git clone https://github.com/neovimhaskell/haskell-vim.git
git clone https://github.com/itchyny/lightline.vim.git
git clone https://github.com/preservim/nerdtree.git
git clone https://github.com/tomtom/tcomment_vim.git











