#!/usr/bin/env bash

#Make this file executable by chmod 700
# Make my .vim directories for plugins and undo history
mkdir -p ~/.vim/pack/plugs/start 
mkdir ~/.vim/undodir 
# Clone the plugins
cd ~/.vim/pack/plugs/start 
git clone https://github.com/vim-scripts/AutoComplPop.git
git clone https://github.com/morhetz/gruvbox.git
git clone https://github.com/neovimhaskell/haskell-vim.git
git clone https://github.com/itchyny/lightline.vim.git
git clone https://github.com/preservim/nerdtree.git
git clone https://github.com/tomtom/tcomment_vim.git











